services:
    app.form.type.login_type:
        class: AppBundle\Form\Type\LoginType
        arguments:
            - @translator.default
        tags:
            - { name: form.type, alias: app_login }
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", @translator.default]

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack", @security.token_storage]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    app.logout_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: createLogoutMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: logout } # The alias is what is used to retrieve the menu
    security.access.user_voter:
        class:      AppBundle\Security\Authorization\Voter\UserVoter
        public:     false
        tags:
           - { name: security.voter }
