AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        email:
            - NotBlank: ~
            - Email: ~
        username:
            - NotBlank: ~
            - Length:
                max: 255
                min: 3
        fullname:
            - NotBlank: ~
        password:
            - Length: { min: 3, groups: [add] }
        file:
            - Image:
                maxSize: 5M

AppBundle\Entity\Role:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: role
    properties:
        role:
            - NotBlank: ~
            - Choice: { choices: [ROLE_OPERATOR, ROLE_MANAGER, ROLE_ADMINISTRATOR] }

AppBundle\Entity\Project:
    properties:
        label:
            - NotBlank: ~
            - Length:
                  max: 255
                  min: 2
        created:
            - DateTime: ~
        updated:
            - DateTime: ~

AppBundle\Entity\Issue:
    properties:
        summary:
            - NotBlank: ~
            - Length:
                  max: 255
                  min: 2
        created:
            - DateTime: ~
        updated:
            - DateTime: ~
AppBundle\Entity\Comment:
    properties:
        created:
            - DateTime: ~
