<?php
namespace AppBundle\Tests\Form\Type;

use AppBundle\Form\Type\CommentType;
use Symfony\Component\Form\Test\TypeTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-28 at 22:01:14.
 */
class CommentTypeTest extends TypeTestCase
{
    /**
     * @var CommentType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CommentType(
            $this->translator = $this->getMockBuilder('Symfony\Component\Translation\TranslatorInterface')->getMock()
        );
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers AppBundle\Form\Type\CommentType::getName
     */
    public function testGetName()
    {
        $this->assertEquals('app_comment', $this->object->getName());
    }

    public function testSubmitValidData()
    {
        $form = $this->factory->create($this->object);
        $formData = [
            'body' => 'test'
        ];
        $form->submit($formData);

        $this->assertTrue($form->isSynchronized());
        $this->assertEquals($formData, $form->getData());

        $view = $form->createView();
        $children = $view->children;

        foreach (array_keys($formData) as $key) {
            $this->assertArrayHasKey($key, $children);
        }
    }
}
