<?php
namespace AppBundle\Tests\Unit\Form\Type;

use AppBundle\Form\Type\UserType;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-24 at 14:56:44.
 */
class UserTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserType(
            $this->getMockBuilder('Symfony\Component\Translation\TranslatorInterface')->getMock()
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers AppBundle\Form\Type\UserType::getName
     */
    public function testGetName()
    {
        $this->assertEquals('app_user', $this->object->getName());
    }

    /**
     * @covers AppBundle\Form\Type\UserType::buildForm
     */
    public function testBuildForm()
    {
        $builder = $this->getMockBuilder('Symfony\Component\Form\FormBuilder')
            ->disableOriginalConstructor()
            ->getMock();
        $builder->expects($this->at(0))->method('add')
            ->willReturn($builder)
            ->with(
                'email',
                'email',
                [
                    'required' => true,
                    'label' => null
                ]
            );
        $builder->expects($this->at(1))->method('add')
            ->willReturn($builder)
            ->with(
                'username',
                'text',
                [
                    'required' => true,
                    'label' => null
                ]
            );
        $builder->expects($this->at(2))->method('add')
            ->willReturn($builder)
            ->with(
                'fullname',
                'text',
                [
                    'required' => true,
                    'label' => null
                ]
            );
        $builder->expects($this->at(2))->method('add')
            ->willReturn($builder)
            ->with(
                'fullname',
                'text',
                [
                    'required' => true,
                    'label' => null
                ]
            );
        $builder->expects($this->at(3))->method('add')
            ->willReturn($builder)
            ->with(
                'file',
                'file',
                [
                    'required' => false,
                    'label' => null
                ]
            );
        $this->object->buildForm($builder, []);
    }
}
